path(route='', view=views.CourseListView.as_view(), name='index'),
path(route='signup/', view=views.registration_request, name='signup'),
path(route='signin/', view=views.login_request, name='signin'),
path(route='logout/', view=views.logout_request, name='logout'),
path(route='<int:pk>/enroll/', view=views.enroll, name='enroll'),
path(route='<int:pk>/course_details/', view=views.CourseDetailView.as_view(), name='course_details'),
path(route='<int:course_id>/submit/', view=views.submit, name='submit'),
path(route='<int:course_id>/submission/<int:submission_id>/result/',
     view=views.show_exam_result, name='exam_result'),
